project_path: .
ddconfig_path: configs/ddconfigs/rainfall.json
model_path: models/sequifier-default-mse-best-1000.onnx
data_path: data/rainfall-split0.parquet

selected_columns: ["Precipitation"]
target_columns: [Precipitation]
target_column_types:
  Precipitation: real

output_probabilities: false
map_to_id: false
device: cpu
seq_length: 8
inference_batch_size: 10

autoregression: false