project_path: .
data_path: data/rainfall.csv
read_format: csv
write_format: parquet
selected_columns: ["Specific Humidity", "Relative Humidity", "Temperature", "Precipitation"]
target_columns: ["Precipitation"]
return_targets: true

group_proportions:
- 0.8
- 0.1
- 0.1
seq_length: 25
max_rows: null