project_path: .
model_name: default-mse
read_format: parquet
ddconfig_path: configs/ddconfigs/rainfall.json

selected_columns: ["Precipitation"]
target_columns: ["Precipitation"]
target_column_types:
  Precipitation: real

seq_length: 8
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 64
  nhead: 4
  d_hid: 64
  nlayers: 4
training_spec:
  device: cpu
  epochs: 1000
  iter_save: 1000
  batch_size: 100
  log_interval: 10000
  lr: 0.0008
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    Precipitation: MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: StepLR
    step_size: 100
    gamma: 0.99
  continue_training: false